# Generated by Django 3.1 on 2020-10-19 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='num_correct_answers',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='num_incorrect_answers',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
