# Generated by Django 3.1 on 2020-10-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0002_auto_20201019_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='points',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
