# Generated by Django 3.1 on 2020-10-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0003_testresult_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='taken_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
