# Generated by Django 3.1 on 2020-10-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0005_auto_20201023_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='taken_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
