# Generated by Django 3.1 on 2020-10-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0006_auto_20201023_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='points',
            field=models.SmallIntegerField(default=0),
        ),
    ]
