# Generated by Django 3.1 on 2020-10-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0008_remove_testresult_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='taken_time',
        ),
    ]
