# Generated by Django 3.1 on 2020-10-25 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0009_remove_testresult_taken_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='score',
        ),
        migrations.AddField(
            model_name='testresult',
            name='current_order_number',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
    ]
