# Generated by Django 3.1 on 2020-11-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testify', '0010_auto_20201025_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answers', to='testify.question')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answers', to='testify.testresult')),
                ('user_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answers', to='testify.answer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
