# Generated by Django 3.1 on 2020-12-21 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testify', '0012_auto_20201101_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
