# Generated by Django 3.1 on 2020-11-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
