# Generated by Django 3.1 on 2020-12-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201123_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='num_emails_received',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
