# Generated by Django 3.1 on 2020-12-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201206_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, default='0000-00-00 00:00:00', null=True),
        ),
    ]
