# Generated by Django 3.1 on 2020-12-06 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201206_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True),
        ),
    ]
