# Generated by Django 3.1 on 2021-01-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='whose',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='whose',
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(max_length=2, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=48, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='skype',
            field=models.CharField(max_length=124, null=True, verbose_name='Skype'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Whose',
        ),
    ]
